version: '3.7'
services:
  mysql_container:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: order-service
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mk
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql
volumes:
  mysql_data_container:
