version: '3.7'
services:
  mysql_container_two:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: inventory-service
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mk
      MYSQL_PASSWORD: password
    ports:
      - "6000:3306"
    volumes:
      - mysql_data_container_two:/var/lib/mysql
volumes:
  mysql_data_container_two:
